CXXFLAGS = \
  -std=c++17 \
  -pedantic \
  -Wall \
  -Wextra \
  -Wconversion \
  -Wsign-conversion \
  -Wshadow \
  -O2

ARTIFACTS = \
  main


.PHONY: all clean

all: main
	@./main

clean:
	rm -f $(ARTIFACTS)
