VM_BOX = "bento/ubuntu-18.04"
VM_IP = "10.0.0.2"
K3S_VERSION = "v0.9.1"

Vagrant.configure("2") do |config|
  config.vm.box = VM_BOX
  config.vm.network :private_network, ip: VM_IP

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision :shell, inline: <<-EOF
    if ! command -v k3s; then
      export INSTALL_K3S_VERSION=#{K3S_VERSION}
      curl -fsSL https://get.k3s.io | sh -
    fi
  EOF
end
