Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-17.10"
  config.vm.hostname = "ubuntu.example.com"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
  end
end
