# Requirement: vagrant plugin install vagrant-vultr dotenv
Dotenv.load

Vagrant.configure("2") do |config|
  config.vm.provider :vultr do |vultr, override|
    vultr.region = ENV["VULTR_REGION"] || "Tokyo"
    vultr.plan   = ENV["VULTR_PLAN"]   || "1024 MB RAM,25 GB SSD,1.00 TB BW"
    vultr.os     = ENV["VULTR_OS"]     || "Debian 9 x64 (stretch)"
    vultr.token  = ENV["VULTR_TOKEN"]
    override.ssh.private_key_path = ENV["VULTR_SSH_KEY"]
    override.vm.box = "vultr"
    override.vm.box_url = "https://github.com/p0deje/vagrant-vultr/raw/master/box/vultr.box"
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "bootstrap.yml"
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
