VM_BOX = "bento/ubuntu-18.04"
EXTERNAL_IP = "10.0.0.2"

Vagrant.configure("2") do |config|
  config.vm.box = VM_BOX
  config.vm.network :private_network, ip: EXTERNAL_IP

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provision.yml"
  end
end
