require 'io/console'

def ask(prompt)
  print prompt
  secret = STDIN.noecho(&:gets)
  print "\n"
  secret
end

SSH_KEY = "~/.ssh/id_rsa-vagrant@vultr.com"
VULTR_API_TOKEN = ENV["VULTR_API_TOKEN"] || ask("API token: ")
VULTR_REGION = ENV["VULTR_REGION"] || "New Jersey"
VULTR_PLAN = ENV["VULTR_PLAN"] || "1024 MB RAM,25 GB SSD,1.00 TB BW"
VULTR_OS = ENV["VULTR_OS"] || "Ubuntu 16.04 x64"
VULTR_BOX = "https://github.com/p0deje/vagrant-vultr/raw/master/box/vultr.box"

Vagrant.configure(2) do |config|
  config.vm.provider :vultr do |vultr, override|
    override.nfs.functional = false
    override.ssh.private_key_path = SSH_KEY
    override.vm.box = "vultr"
    override.vm.box_url = VULTR_BOX

    vultr.token = VULTR_API_TOKEN
    vultr.region = VULTR_REGION
    vultr.plan = VULTR_PLAN
    vultr.os = VULTR_OS
  end
end
