VM_CPUS = 1
VM_MEMORY = 512
SERVER_BOX = "debian/buster64"
CLIENT_BOX = "debian/buster64"
SERVER_IP = "10.162.55.10"
CLIENT_IP = "10.162.55.11"

Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |v|
    v.cpus = VM_CPUS
    v.memory = VM_MEMORY
  end

  config.vm.define "n-server" do |server|
    server.vm.box = SERVER_BOX
    server.vm.network :private_network, ip: SERVER_IP
    server.vm.provision :ansible do |ansible|
      ansible.playbook = "provision_server.yml"
      ansible.extra_vars = {
        nfs_server: SERVER_IP
      }
    end
  end

  config.vm.define "n-client" do |client|
    client.vm.box = CLIENT_BOX
    client.vm.network :private_network, ip: CLIENT_IP
    client.vm.provision :ansible do |ansible|
      ansible.playbook = "provision_client.yml"
      ansible.extra_vars = {
        nfs_server: SERVER_IP
      }
    end
  end
end
