VM_BOX = "bento/ubuntu-18.04"
VM_IP = "192.168.119.2"
VM_CPUS = 2
VM_MEMORY = 2048

Vagrant.configure("2") do |config|
  config.vm.box = VM_BOX
  config.vm.network :private_network, ip: VM_IP

  config.vm.provider "virtualbox" do |v|
    v.cpus = VM_CPUS
    v.memory = VM_MEMORY
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provision.yml"
    ansible.extra_vars = {
      private_network: "#{VM_IP}/24"
    }
  end
end
