CXXFLAGS = \
  -std=c++17 \
  -pedantic \
  -Wall \
  -Wextra \
  -Wconversion \
  -Wsign-conversion \
  -Wno-c99-extensions \
  -isystem ../deps/micromd/include \
  -O2

.PHONY: all clean

all: main
	@:

clean:
	rm -f main
