Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "setup.yml"
  end
end
