DISK_NAME = "_disk.vdi"
DISK_SIZE = 20 * 1024

Vagrant.configure("2") do |config|
  config.vm.box = "freebsd/FreeBSD-12.0-RELEASE"

  config.vm.provider :virtualbox do |v|
    v.customize [
      "createhd",
      "--filename", DISK_NAME,
      "--format", "VDI",
      "--size", DISK_SIZE
    ]
    v.customize [
      "storageattach",
      :id,
      "--storagectl", "IDE Controller",
      "--port", 1,
      "--device", 0,
      "--type", "hdd",
      "--medium", DISK_NAME
    ]
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provision.yml"
  end

  config.ssh.shell = "/bin/sh"
end
