Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "web.example.com"
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "web.yml"
    ansible.verbose = "vv"
  end
end
