VM_BOX = "bento/ubuntu-18.04"
VM_IP = "192.168.119.2"
VM_MEMORY = 4096
VM_CPUS = 2

Vagrant.configure("2") do |config|
  config.vm.box = VM_BOX
  config.vm.network :private_network, ip: VM_IP

  config.vm.provider "virtualbox" do |v|
    v.memory = VM_MEMORY
    v.cpus = VM_CPUS
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provision.yml"
    ansible.extra_vars = {
      k3s_address: VM_IP
    }
  end
end
