Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "gene" do |machine|
    machine.vm.hostname = "gene.gene.example.com"
    machine.vm.network "private_network", ip: "172.16.0.100", netmask: "255.255.255.0"
  end

  config.vm.define "gene01" do |machine|
    machine.vm.hostname = "gene01.gene.example.com"
    machine.vm.network "private_network", ip: "172.16.0.1", netmask: "255.255.255.0"
  end

  config.vm.define "gene02" do |machine|
    machine.vm.hostname = "gene02.gene.example.com"
    machine.vm.network "private_network", ip: "172.16.0.2", netmask: "255.255.255.0"
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provision.yml"
    ansible.groups = {
      "worker" => ["gene01", "gene02"]
    }
  end
end
