Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "ansible/provision.yml"
    ansible.extra_vars = {ansible_python_interpreter: "python3"}
  end
end
