Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "gene01"
  config.vm.provision :ansible do |ansible|
    ansible.groups = {"gene" => ["gene01"]}
    ansible.playbook = "worker-node.yml"
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
