Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "web.example.com"
  config.vm.network "forwarded_port", guest: 80, host: 16780
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "web.yml"
  end
end
