# https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=201904
FREEBSD_BASE_MAC = "080027D14C66"

Vagrant.configure("2") do |config|
  config.vm.box = "freebsd/FreeBSD-11.2-RELEASE"
  config.vm.base_mac = FREEBSD_BASE_MAC
  config.ssh.shell = "/bin/sh"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end
end
