Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"

  config.vm.network "forwarded_port", guest: 10022, host: 10022
  config.vm.network "forwarded_port", guest: 10080, host: 10080

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provision.yml"
  end
end
