Vagrant.configure("2") do |config|
  config.vm.box = "freebsd/FreeBSD-12.0-RELEASE"
  config.vm.provider :virtualbox
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provision.yml"
  end
  config.ssh.shell = "/bin/sh"
end
