Vagrant.configure("2") do |config|
  config.vm.box = "generic/freebsd12"
  config.vm.network "private_network", ip: "192.168.231.10"
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provision.yml"
  end
end
