Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define "master" do |config|
    config.vm.network "private_network", ip: "172.16.0.10"
  end

  config.vm.define "worker" do |config|
    config.vm.network "private_network", ip: "172.16.0.11"
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provision.yml"
    ansible.extra_vars = {
      "nis_domain" => "mynisdomain",
      "nis_server" => "master",
      "static_ips" => {
        "master" => "172.16.0.10",
        "worker" => "172.16.0.11"
      }
    }
  end
end
