NAME =                  ubuntu-zfs
VERSION =               {{ ansible_lsb.codename }}
TITLE =                 Ubuntu with ZFS
DEFAULT_IMAGE_ARCH =    x86_64

IMAGE_VOLUME_SIZE =     50G
IMAGE_BOOTSCRIPT =      {{ scw_bootscript }}

all: docker-rules.mk

docker-rules.mk:
	curl -fsSLO "https://raw.githubusercontent.com/scaleway/image-tools/master/builder/docker-rules.mk"

-include docker-rules.mk
