# Require: vagrant plugin install vagrant-scaleway dotenv

Dotenv.load

DEFAULT_REGION = "par1"
DEFAULT_PLAN = "C2S"
DEFAULT_VOLUME = 50_000_000_000

# UUID obtained from: https://cp-par1.scaleway.com/images
DEFAULT_BUILDER_IMAGE = "9c91c96f-7fc5-4224-96fb-cf8d55422934" # Image Builder 1.4.3

# UUID obtained from: https://cp-par1.scaleway.com/bootscripts
DEFAULT_BOOTSCRIPT = "59c77041-6b3b-43c2-99c9-2d764bf0e326" # x86_64 mainline 4.4.112 rev1

SCW_REGION = ENV["SCW_REGION"] || DEFAULT_REGION
SCW_PLAN = ENV["SCW_PLAN"] || DEFAULT_PLAN
SCW_VOLUME = ENV["SCW_VOLUME"] || DEFAULT_VOLUME
SCW_IMAGE = ENV["SCW_IMAGE"] || DEFAULT_BUILDER_IMAGE
SCW_BOOTSCRIPT = ENV["SCW_BOOTSCRIPT"] || DEFAULT_BOOTSCRIPT
SCW_PRIVKEY = ENV["SCW_PRIVKEY"]

Vagrant.configure("2") do |config|
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "builder.yml"
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :scaleway do |scaleway, override|
    scaleway.region = SCW_REGION
    scaleway.commercial_type = SCW_PLAN
    scaleway.image = SCW_IMAGE
    scaleway.bootscript = SCW_BOOTSCRIPT
    scaleway.volumes = [
      { size: SCW_VOLUME.to_i }
    ]
    override.ssh.private_key_path = SCW_PRIVKEY
  end
end
