Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.synced_folder ".", "/vagrant", disabled: true

# config.vm.provision :ansible do |ansible|
#   ansible.playbook = "provision.yml"
#   ansible.extra_vars = {
#     ansible_python_interpreter: "/usr/bin/python3"
#   }
# end
end
