VM_BOX = "bento/ubuntu-18.04"
EXTERNAL_IP = "10.0.0.2"

Vagrant.configure("2") do |config|
  config.vm.box = VM_BOX
  config.vm.network :private_network, ip: EXTERNAL_IP

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision :shell, inline: <<-EOF
    export INSTALL_K3S_VERSION=v0.8.0
    export INSTALL_RIO_VERSION=v0.4.0-rc2
    ( curl -fsSL https://get.k3s.io | sh - ) &
    ( curl -fsSL https://get.rio.io | sh - ) &
    wait
    rio install --ip-address #{EXTERNAL_IP} --lite
  EOF

  # FAQ [1] says upgrading Rio can be done simplly by running `rio install`
  # again with an upgraded CLI. However, installation of control plane fails
  # when upgrading Rio v0.3.2 to v0.4.0-rc1. Need to uninstall first and then
  # install again. Maybe it's not robust yet.
  #
  # Is it much easier to do an immutable installation?
  #
  # So to upgrade Rio immutablly. We need to spin up a new server, install Rio,
  # deploy apps, and then when the apps are up switch the DNS record to point
  # to the new server. This can be automated with Terraform and Ansible.
  #
  # But wait! Can we use the old K3s cluster from the new server? If we can't,
  # we need to set up another cluster to upgrade Rio. That's bad.
  #
  # [1]: https://github.com/rancher/rio/blob/master/docs/README.md
end
